title: Qoxmfaktmxj Blog
description: "Daily automated AI news and dev study notes"
url: "https://qoxmfaktmxj.github.io"
baseurl: ""
lang: en
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
show_excerpts: true
